contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://github.com/lazyforme/daydayup"
title: "LazyForMe"
theme: "ananke"
canonifyurls: true
